service: vue-graphql-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-2

plugins:
  - serverless-appsync-plugin

custom:
  appSync:
    name: vue-graphql-api
    authenticationType: API_KEY
    apiKeys:
      - name: default
        description: Default API Key
        expiresAfter: 365d
    dataSources:
      - type: AMAZON_DYNAMODB
        name: TodoTable
        config:
          tableName: !Ref TodoTable
    mappingTemplates:
      - dataSource: TodoTable
        type: Query
        field: listTodos
        request: |
          {
            "version": "2017-02-28",
            "operation": "Scan"
          }
        response: |
          $util.toJson($context.result.items)
      - dataSource: TodoTable
        type: Mutation
        field: createTodo
        request: |
          {
            "version": "2017-02-28",
            "operation": "PutItem",
            "key": {
              "id": $util.dynamodb.toDynamoDBJson($util.autoId())
            },
            "attributeValues": $util.dynamodb.toMapValuesJson($context.arguments.input)
          }
        response: |
          $util.toJson($context.result)

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

  Outputs:
    GraphQLApiUrl:
      Value: !GetAtt GraphQlApi.GraphQLUrl
    GraphQLApiKey:
      Value: !GetAtt GraphQlApiKeyDefault.ApiKey