-- CONFIG_PARAM table creation/update script
CREATE TABLE IF NOT EXISTS `CONFIG_PARAM` (
  `CONFIG_PARAM_ID` int NOT NULL AUTO_INCREMENT,
  `CONFIG_NAME` varchar(256) NOT NULL,
  `CONFIG_VALUE` varchar(256) NOT NULL,
  `DESCRIPTION` varchar(256) DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`CONFIG_PARAM_ID`),
  UNIQUE KEY `UK_CONFIG_NAME` (`CONFIG_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;