-- FILTER_CRITERIA table creation/update script
-- NOTE: This table is for database use only - excluded from GraphQL/App per table_config.json

CREATE TABLE IF NOT EXISTS `FILTER_CRITERIA` (
  `FILTER_CRITERIA_ID` INT NOT NULL AUTO_INCREMENT,
  `ORIGIN_PRODUCT_ID` INT NOT NULL,
  `STEP_TYPE_ID` INT NOT NULL,
  `CRITERIA` TEXT NOT NULL,
  `SEQUENCE_NBR` INT NOT NULL,
  `CREATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGED_DATE` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`FILTER_CRITERIA_ID`),
  UNIQUE INDEX `UK_FILTER_CRITERIA` (`ORIGIN_PRODUCT_ID` ASC, `STEP_TYPE_ID` ASC, `SEQUENCE_NBR` ASC),
  INDEX `FK_FILTER_STEP_TYPE_ID` (`STEP_TYPE_ID` ASC),
  CONSTRAINT `FK_FILTER_ORIGIN_PRODUCT_ID`
    FOREIGN KEY (`ORIGIN_PRODUCT_ID`)
    REFERENCES `ORIGIN_PRODUCT` (`ORIGIN_PRODUCT_ID`),
  CONSTRAINT `FK_FILTER_STEP_TYPE_ID`
    FOREIGN KEY (`STEP_TYPE_ID`)
    REFERENCES `STEP_TYPE` (`STEP_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;