-- LOAN_APP_EXECS table creation/update script
CREATE TABLE IF NOT EXISTS `LOAN_APP_EXECS` (
  `LOAN_APP_EXEC_ID` int NOT NULL AUTO_INCREMENT,
  `LOAN_APP_ID` int NOT NULL,
  `AWS_EXEC_ID` varchar(256) NOT NULL,
  `CREATED_DATE` timestamp NOT NULL,
  PRIMARY KEY (`LOAN_APP_EXEC_ID`),
  KEY `FK_LOAN_APP` (`LOAN_APP_ID`),
  CONSTRAINT `FK_LOAN_APP` FOREIGN KEY (`LOAN_APP_ID`) REFERENCES `LOAN_APP` (`LOAN_APP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;