-- LOAN_APP table creation/update script
CREATE TABLE IF NOT EXISTS `LOAN_APP` (
  `LOAN_APP_ID` INT NOT NULL AUTO_INCREMENT,
  `ORIGIN_LOAN_APP_ID` VARCHAR(100) NOT NULL,
  `ORIGIN_PRODUCT_ID` INT NOT NULL,
  `PROCESS_FLAG` CHAR(1) NOT NULL COMMENT 'flag to indicate if loan application process was completed',
  `EXEC_ID` VARCHAR(255) NULL DEFAULT NULL COMMENT 'Step Function Execution ID',
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `CHANGED_DATE` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`LOAN_APP_ID`),
  UNIQUE INDEX `UK_LOAN_APP` (`ORIGIN_LOAN_APP_ID` ASC, `ORIGIN_PRODUCT_ID` ASC),
  INDEX `R_LOAN_APPP_ORIGIN_PRODUCT` (`ORIGIN_PRODUCT_ID` ASC),
  CONSTRAINT `R_LOAN_APPP_ORIGIN_PRODUCT`
    FOREIGN KEY (`ORIGIN_PRODUCT_ID`)
    REFERENCES `ORIGIN_PRODUCT` (`ORIGIN_PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;