-- LOAN_APP_STEP_STATUS table creation/update script
CREATE TABLE IF NOT EXISTS `LOAN_APP_STEP_STATUS` (
  `LOAN_APP_STEP_STATUS_ID` int NOT NULL AUTO_INCREMENT,
  `LOAN_APP_ID` int NOT NULL,
  `LOAN_APP_EXEC_ID` int DEFAULT NULL,
  `STEP_TYPE_ID` int NOT NULL,
  `COMPLETE_FLAG` char(1) NOT NULL DEFAULT 'N',
  `SEQUENCE_NBR` int NOT NULL,
  `IDX_JSON_PATH` varchar(255) DEFAULT NULL,
  `RESPONSE_TEXT` varchar(1000) DEFAULT NULL,
  `OUTPUT_JSON` varchar(10000) DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`LOAN_APP_STEP_STATUS_ID`),
  KEY `FK_LOAN_APP_EXEC_ID` (`LOAN_APP_EXEC_ID`),
  KEY `R_LOAN_APP_STEP_STATUS_LOANAPP_idx` (`LOAN_APP_ID`),
  KEY `R_LOAN_APP_STEP_STATUS_STEPTYP_idx` (`STEP_TYPE_ID`),
  CONSTRAINT `FK_LOAN_APP_EXEC_ID` FOREIGN KEY (`LOAN_APP_EXEC_ID`) REFERENCES `LOAN_APP_EXECS` (`LOAN_APP_EXEC_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;