-- NEW_MEMBER_TOKEN table creation/update script
CREATE TABLE IF NOT EXISTS `NEW_MEMBER_TOKEN` (
  `NEW_MEMBER_TOKEN_ID` INT NOT NULL AUTO_INCREMENT,
  `MEMBER_NBR` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Member number generated specific to FI',
  `CARD_NBR` VARCHAR(16) NULL DEFAULT NULL,
  `PERSON_NBR` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Person number provided by FI',
  `LOAN_APP_ID` INT NOT NULL,
  `FIRST_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `LAST_NAME` VARCHAR(40) NULL DEFAULT NULL,
  `DOB` VARCHAR(20) NULL DEFAULT NULL,
  `TAX_ID` VARCHAR(10) NULL DEFAULT NULL,
  `EMAIL_ADDRESS_TEXT` VARCHAR(100) NULL DEFAULT NULL,
  `ZIP_CODE` VARCHAR(10) NULL DEFAULT NULL,
  `HOME_PHONE_NBR` VARCHAR(15) NULL DEFAULT NULL,
  `MOBILE_PHONE_NBR` VARCHAR(15) NULL DEFAULT NULL,
  `TOKEN_VALUE` VARCHAR(36) NULL DEFAULT NULL,
  `TOKEN_USED_FLAG` CHAR(1) NOT NULL,
  `CREATED_DATE` TIMESTAMP NOT NULL,
  `CHANGED_DATE` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`NEW_MEMBER_TOKEN_ID`),
  INDEX `R_NEW_MEMBER_TOKEN_LOAN_APP` (`LOAN_APP_ID` ASC),
  CONSTRAINT `R_NEW_MEMBER_TOKEN_LOAN_APP`
    FOREIGN KEY (`LOAN_APP_ID`)
    REFERENCES `LOAN_APP` (`LOAN_APP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;