CREATE TABLE IF NOT EXISTS `ORIGIN_PRODUCT` (
  `ORIGIN_PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `VENDOR_NAME` VARCHAR(50) NOT NULL,
  `PRODUCT_ID` VARCHAR(50) NOT NULL COMMENT 'Unique Identifier configured by the vendor under a specific client',
  `PSCU_CLIENT_ID` INT NOT NULL,
  `PRODUCT_DESC` VARCHAR(200) NOT NULL,
  `PARTNER_CODE` VARCHAR(10) NULL DEFAULT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`ORIGIN_PRODUCT_ID`),
  UNIQUE INDEX `UK_ORIGIN_PRODUCT` (`VENDOR_NAME` ASC, `PRODUCT_ID` ASC, `PSCU_CLIENT_ID` ASC) VISIBLE,
  INDEX `idx_pscu_client_id` (`PSCU_CLIENT_ID` ASC) VISIBLE,
  INDEX `idx_origin_product_id` (`ORIGIN_PRODUCT_ID` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 95
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List of Origination products from different vendors. example Amount ';