-- REDIRECT_URL table creation/update script
CREATE TABLE IF NOT EXISTS `REDIRECT_URL` (
  `REDIRECT_URL_ID` INT NOT NULL AUTO_INCREMENT,
  `ORIGIN_PRODUCT_ID` INT NOT NULL,
  `URL_TYPE_CODE` CHAR(1) NOT NULL COMMENT 'New or Existing Members',
  `URL` VARCHAR(255) NOT NULL,
  `RESPONSE_TEXT` VARCHAR(1024) NULL DEFAULT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`REDIRECT_URL_ID`),
  UNIQUE INDEX `UK_REDIRECT_URL` (`ORIGIN_PRODUCT_ID` ASC, `URL_TYPE_CODE` ASC),
  CONSTRAINT `R_REDIRECT_URL_ORIGIN_PRODUCT`
    FOREIGN KEY (`ORIGIN_PRODUCT_ID`)
    REFERENCES `ORIGIN_PRODUCT` (`ORIGIN_PRODUCT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;