-- SERVICE_PARAM table creation/update script
CREATE TABLE IF NOT EXISTS `SERVICE_PARAM` (
  `SERVICE_PARAM_ID` INT NOT NULL AUTO_INCREMENT,
  `SERVICE_ID` INT NOT NULL,
  `PARAM_NAME` VARCHAR(200) NOT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_PARAM_ID`),
  UNIQUE INDEX `UK_SERVICE_PARAM` (`SERVICE_ID` ASC, `PARAM_NAME` ASC),
  INDEX `I1_SERVICE_PARAM` (`SERVICE_ID` ASC),
  CONSTRAINT `R_SERVICE_PARAM_SERVICE`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `SERVICE` (`SERVICE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;