CREATE TABLE IF NOT EXISTS `SERVICE_PARAM_MAPPING` (
  `SERVICE_PARAM_MAPPING_ID` INT NOT NULL AUTO_INCREMENT,
  `ORIGIN_PRODUCT_ID` INT NOT NULL,
  `SYSTEM_NBR` CHAR(4) NULL DEFAULT NULL,
  `PRIN_NBR` CHAR(4) NULL DEFAULT NULL,
  `AGENT_NBR` CHAR(4) NULL DEFAULT NULL,
  `SOURCE_SERVICE_PARAM_ID` INT NOT NULL,
  `TARGET_SERVICE_PARAM_ID` INT NOT NULL,
  `PLASTIC_TYPE_ID` VARCHAR(50) NULL DEFAULT NULL,
  `COMMENT_TEXT` VARCHAR(500) NULL DEFAULT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_PARAM_MAPPING_ID`),
  UNIQUE INDEX `UK_SERVICE_PARAM_MAPPING` (`ORIGIN_PRODUCT_ID` ASC, `SYSTEM_NBR` ASC, `PRIN_NBR` ASC, `AGENT_NBR` ASC, `SOURCE_SERVICE_PARAM_ID` ASC, `TARGET_SERVICE_PARAM_ID` ASC) VISIBLE,
  INDEX `I1_SERVICE_PARAM_MAPPING` (`ORIGIN_PRODUCT_ID` ASC) VISIBLE,
  INDEX `I2_SERVICE_PARAM_MAPPING` (`SOURCE_SERVICE_PARAM_ID` ASC) VISIBLE,
  INDEX `I3_SERVICE_PARAM_MAPPING` (`TARGET_SERVICE_PARAM_ID` ASC) VISIBLE,
  CONSTRAINT `R_SERVICE_PARAM_MAPPING_SRC`
    FOREIGN KEY (`SOURCE_SERVICE_PARAM_ID`)
    REFERENCES `SERVICE_PARAM` (`SERVICE_PARAM_ID`),
  CONSTRAINT `R_SERVICE_PARAM_MAPPING_TGT`
    FOREIGN KEY (`TARGET_SERVICE_PARAM_ID`)
    REFERENCES `SERVICE_PARAM` (`SERVICE_PARAM_ID`),
  CONSTRAINT `R_SRV_PARAM_MPNG_ORGIN_PRODUCT`
    FOREIGN KEY (`ORIGIN_PRODUCT_ID`)
    REFERENCES `ORIGIN_PRODUCT` (`ORIGIN_PRODUCT_ID`))
ENGINE = InnoDB
AUTO_INCREMENT = 5263
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'This table has maaping for a specific Source to Target Parm and the param is specific to a service provider. This mapping can be at a client/Product/card program grain. It is a 1 to many relation between Source to Target parm';