-- SERVICE_EXPR_MAPPING table creation/update script
CREATE TABLE IF NOT EXISTS `SERVICE_EXPR_MAPPING` (
  `SERVICE_EXPR_MAPPING_ID` INT NOT NULL AUTO_INCREMENT,
  `SERVICE_PARAM_MAPPING_ID` INT NOT NULL,
  `SOURCE_EXPR` VARCHAR(100) NULL DEFAULT NULL,
  `TARGET_EXPR` VARCHAR(100) NULL DEFAULT NULL,
  `COMMENT_TEXT` VARCHAR(500) NULL DEFAULT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_EXPR_MAPPING_ID`),
  UNIQUE INDEX `UK_SERVICE_EXPR_MAPPING` (`SERVICE_PARAM_MAPPING_ID` ASC, `SOURCE_EXPR` ASC, `TARGET_EXPR` ASC),
  CONSTRAINT `R_SERVICE_EXPR_MAPPING_PARM`
    FOREIGN KEY (`SERVICE_PARAM_MAPPING_ID`)
    REFERENCES `SERVICE_PARAM_MAPPING` (`SERVICE_PARAM_MAPPING_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;