-- SERVICE table creation/update script
CREATE TABLE IF NOT EXISTS `SERVICE` (
  `SERVICE_ID` INT NOT NULL AUTO_INCREMENT,
  `SERVICE_PROVIDER_ID` INT NOT NULL COMMENT 'Lists Internal and external service providers for Services that use dynamic mapping parameters',
  `URI` VARCHAR(255) NOT NULL,
  `SECRET_NAME` VARCHAR(256) NULL DEFAULT NULL,
  `REQUEST_TYPE` VARCHAR(50) NULL DEFAULT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_ID`),
  UNIQUE INDEX `UK_SERVICE` (`SERVICE_PROVIDER_ID` ASC, `URI` ASC),
  CONSTRAINT `R_SERVICE_SERVICE_PROVIDER`
    FOREIGN KEY (`SERVICE_PROVIDER_ID`)
    REFERENCES `SERVICE_PROVIDER` (`SERVICE_PROVIDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;