-- SERVICE_DOMAIN table creation/update script
CREATE TABLE IF NOT EXISTS `SERVICE_DOMAIN` (
  `SERVICE_DOMAIN_ID` int NOT NULL AUTO_INCREMENT,
  `DOMAIN_URL` varchar(256) DEFAULT NULL,
  `SERVICE_PROVIDER_ID` int NOT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `CHANGED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SERVICE_DOMAIN_ID`),
  KEY `FK_SERVICE_PROVIDER` (`SERVICE_PROVIDER_ID`),
  CONSTRAINT `FK_SERVICE_PROVIDER` FOREIGN KEY (`SERVICE_PROVIDER_ID`) REFERENCES `SERVICE_PROVIDER` (`SERVICE_PROVIDER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;