-- SERVICE_PROVIDER table creation/update script
CREATE TABLE IF NOT EXISTS `SERVICE_PROVIDER` (
  `SERVICE_PROVIDER_ID` INT NOT NULL AUTO_INCREMENT COMMENT 'Lists Internal and external service providers for Services that use dynamic mapping parameters',
  `SERVICE_PROVIDER_NAME` VARCHAR(50) NOT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`SERVICE_PROVIDER_ID`),
  UNIQUE INDEX `UK_SERVICE_PROVIDER` (`SERVICE_PROVIDER_NAME` ASC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;