CREATE TABLE IF NOT EXISTS `STEP_TYPE` (
  `STEP_TYPE_ID` INT NOT NULL AUTO_INCREMENT,
  `STEP_TYPE_NAME` VARCHAR(50) NOT NULL,
  `STEP_TYPE_DESC` VARCHAR(255) NULL DEFAULT NULL,
  `RESOURCE_NAME` VARCHAR(50) NOT NULL,
  `CREATED_BY_USER_ID` INT NOT NULL,
  `CREATED_DATE` DATE NOT NULL,
  `CHANGED_BY_USER_ID` INT NULL DEFAULT NULL,
  `CHANGED_DATE` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`STEP_TYPE_ID`),
  UNIQUE INDEX `UK_STEP_TYPE` (`STEP_TYPE_NAME` ASC, `RESOURCE_NAME` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 72
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci
COMMENT = 'List of steps in a process';