-- STEP_SERVICE_MAPPING table creation/update script
CREATE TABLE IF NOT EXISTS `STEP_SERVICE_MAPPING` (
  `STEP_SERVICE_MAPPING_ID` INT NOT NULL AUTO_INCREMENT,
  `STEP_TYPE_ID` INT NOT NULL,
  `SERVICE_ID` INT NOT NULL,
  `SEQUENCE_NBR` INT NULL DEFAULT NULL,
  PRIMARY KEY (`STEP_SERVICE_MAPPING_ID`),
  UNIQUE INDEX `UK_STEP_SERVICE_MAPPING` (`STEP_TYPE_ID` ASC, `SERVICE_ID` ASC),
  INDEX `R_STEP_SERVICE_MAPPING_SERVICE` (`SERVICE_ID` ASC),
  CONSTRAINT `R_STEP_SERVICE_MAPPING_SERVICE`
    FOREIGN KEY (`SERVICE_ID`)
    REFERENCES `SERVICE` (`SERVICE_ID`),
  CONSTRAINT `R_STEP_SERVICE_MAPPING_STEP_TY`
    FOREIGN KEY (`STEP_TYPE_ID`)
    REFERENCES `STEP_TYPE` (`STEP_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;