-- STEP_TYPE_PARAM_MAP table creation/update script
CREATE TABLE IF NOT EXISTS `STEP_TYPE_PARAM_MAP` (
  `STEP_TYPE_PARAM_MAP_ID` int NOT NULL AUTO_INCREMENT,
  `STEP_TYPE_ID` int DEFAULT NULL,
  `SERVICE_PARAM_MAPPING_ID` int NOT NULL,
  `CREATED_BY_USER_ID` varchar(100) DEFAULT NULL,
  `CREATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`STEP_TYPE_PARAM_MAP_ID`),
  KEY `FK_PSTPM_STEP_TYPE` (`STEP_TYPE_ID`),
  KEY `FK_PSTPM_SPM` (`SERVICE_PARAM_MAPPING_ID`),
  CONSTRAINT `FK_PSTPM_SPM` FOREIGN KEY (`SERVICE_PARAM_MAPPING_ID`) REFERENCES `SERVICE_PARAM_MAPPING` (`SERVICE_PARAM_MAPPING_ID`),
  CONSTRAINT `FK_PSTPM_STEP_TYPE` FOREIGN KEY (`STEP_TYPE_ID`) REFERENCES `STEP_TYPE` (`STEP_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;