openapi: 3.0.3
info:
  title: NXTsoft Account
  description: >
    <br/>

    Service for creating/reserving account numbers and querying account history.

    <br/>

    <br/>

    <h1>Change Log</h1>


    |Change
    Date|Version|Operations|Description                                                                                                        
    |

    |--------------------|-------|---------------|--------------------------------------------------------------------------------------------|

    |03/17/2025|1.1.14|All APIs|Consolidate coreSpecificFields to master list
    per API call (example AllNonStandardFields_AccountHistory). Core filters to
    remain in place. Add descriptions to consolidated fields list indicating
    core utilization.|

    |02/07/2023|1.1.13|Account|Add Phoenix specific field outputDepLoan.|

    |10/24/2022|1.1.12|Account|Sidebar consolidation.|

    |09/09/2022|1.1.11|Account|Shorten and update core specific field names. AC
    (Account Create), AH (Acount History).|

    |09/02/2022|1.1.9|Account|Enable specification download. Move API
    description to info block.|

    |08/01/2022|1.1.8|Account|Move Domain references to internal references:
    accountType.|

    |07/08/2022|1.1.7|Account-history|Change JXChange specific field
    'memoPostRmk' to 'remarks'.

    |07/09/2022|1.1.6|Account-history|Add eftDescriptionArray to
    AccountHistoryRs.|

    |06/29/2022|1.1.5|Account-history|Add JXChange specific field memoPost to
    AccountHistoryRs. Add enums for 'status' in AccountHistoryRs:
    TransactionDetails. Add fields to interestRateInfo in AccountHistoryRs.|

    |06/22/2022|1.1.4|Account-history|Add SymXChange field shareID in
    SymXChangeSpecificFieldsAccountHistory.|

    |06/02/2022|1.1.3|Account|Review and update API field descriptions.|

    |05/11/2022|1.1.2|Account-history|Add uuid and status fields to account
    history.|

    |04/01/2022|1.1.1|Account-history|Add account-history search.|

    |03/16/2022|1.0.1|All|Update redocly CLI and change domain name for $refs.|

    |01/10/2022|1.1.0|Account-number|Add datapoints needed for SymXChange. 
    openDate, lastName and preferenceType.| 

    |11/11/2021|1.0.1|Account-number|Remove dev server link and organize the
    servers in the following order: Test, Prod.|  
  contact:
    name: API Support
    email: apisupport@nxtsoft.com
    url: https://omniportal.nxtsoft.com/
  version: v1
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: /assets/omni_connect.png
servers:
  - url: https://api-test.nxtsoft.com/v1/account
    description: Test Based URL
  - url: https://api.nxtsoft.com/v1/account
    description: Production Based URL
paths:
  /account-number:
    post:
      tags:
        - Account Operations
      operationId: accountNumber
      summary: Reserve a New Account Number.
      requestBody:
        description: Request to reserve new account number(s).
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NextAccountNumberRq'
        required: true
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NextAccountNumberRs'
  /account-history:
    post:
      tags:
        - Account History Operations
      operationId: accountHistory
      summary: Search Transacation History.
      requestBody:
        description: Request for transaction history.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountHistoryRq'
        required: true
      responses:
        '200':
          description: Successful operation.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountHistoryRs'
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://auth.nxtsoft.com/oauth2/token
          scopes: {}
  schemas:
    accountType:
      type: string
      description: Type of account.
      enum:
        - CD
        - Checking
        - IRA
        - Line
        - Loan
        - MoneyMarket
        - Other
        - Savings
        - Stock
        - Gift
    NextAccountNumberRq:
      type: object
      properties:
        assetID:
          type: string
          description: >-
            A specific software-based key for identifying a client utilizing the
            Omni Platform. NXTsoft provides the unique value to the partner,
            vendor, or client.
        content:
          type: object
          properties:
            accountType:
              $ref: '#/components/schemas/accountType'
            branchNumber:
              type: string
              description: Identifies the financial institution branch.
            officerCode:
              type: string
              description: Identifies the banking officer associated with this account.
            productCode:
              type: string
              description: Identifies the product type for this account.
            quantity:
              type: integer
              description: Number of account numbers requested.
            subAccountType:
              type: string
              description: Subordinate category of account type.
            coreSpecificFields:
              oneOf:
                - $ref: >-
                    #/components/schemas/AllNonStandardFields_AccountNumberGenerator
                - $ref: '#/components/schemas/SymXChangeAC'
                - $ref: '#/components/schemas/PhoenixAC'
        uuid:
          type: string
          description: Unique identifier for the request.
      required:
        - assetID
    NextAccountNumberRs:
      type: object
      properties:
        content:
          description: List of account numbers
          type: array
          items:
            type: string
            description: Account numbers reserved.
        statusCode:
          type: number
          description: Reference the `Codes` table.
        statusFlag:
          type: boolean
          description: >-
            Returns `true` if the post is successful. Returns `false` if any
            errors are encountered.
        statusMessage:
          type: string
          description: Details of the request `success` or `errors`.
        uuid:
          type: string
          description: Unique identifier for the request.
    AccountHistoryRq:
      type: object
      properties:
        assetID:
          type: string
          description: >-
            A specific software-based key for identifying a client utilizing the
            Omni Platform. NXTsoft provides the unique value to the partner,
            vendor, or client.
        content:
          type: object
          properties:
            accountNumber:
              type: string
              description: Account number for selection of transaction history.
            accountType:
              type: string
              description: Type of account for selection of transaction history.
            coreSpecificFields:
              oneOf:
                - $ref: '#/components/schemas/AllNonStandardFields_AccountHistoryRq'
                - $ref: '#/components/schemas/SymXChangeAH'
            startDate:
              type: string
              format: date
              description: Start date for transaction history selection (inclusive).
            endDate:
              type: string
              format: date
              description: End date for transaction history selection (inclusive).
        uuid:
          type: string
          description: Unique identifier for the request.
      required:
        - assetID
    AccountHistoryRs:
      type: object
      description: >-
        Returns account, interest rate and balance information with an array of
        transacion detail.
      properties:
        content:
          type: object
          properties:
            AccountInfo:
              type: object
              description: Account related information.
              properties:
                accountID:
                  type: string
                  description: Account selected for inquiry.
                accountType:
                  type: string
                  description: Type of account selected.
                currentBalance:
                  type: number
                  format: double
                  description: Current balance of the account.
            InterestRateInfo:
              type: object
              description: Interest rate information.
              properties:
                accrualMethod:
                  type: string
                  description: Interest accrual method for the account.
                index:
                  type: number
                  format: double
                  description: Indicates the index the account is tied to for rate reviews.
                interestRate:
                  type: number
                  format: double
                  description: Interest rate on the account.
                rateEffectiveDate:
                  type: string
                  format: date
                  description: >-
                    Date the stated rate became effective. Opening date for
                    fixed rate accounts or date of last rate change for variable
                    rate accounts.
                rateReviewDate:
                  type: string
                  format: date
                  description: The date on which the acount is reviewed for a rate change.
                rateReviewTerm:
                  type: number
                  description: Defines the length of time between rate reviews.
                rateReviewTermUnits:
                  type: string
                  description: Time units used in determining the next rate change date.
                rateVariance:
                  type: number
                  format: double
                  description: Amount the interest rate varies from the index.
                rateVarianceCode:
                  type: string
                  description: Indicates if the variance is above or below the prime rate.
            TransactionDetails:
              type: array
              description: Detailed transaction history.
              items:
                type: object
                properties:
                  amount:
                    type: number
                    format: double
                    description: Value of the transaction.
                  coreSpecificFields:
                    oneOf:
                      - $ref: >-
                          #/components/schemas/AllNonStandardFields_AccountHistoryRs
                      - $ref: '#/components/schemas/JH2020AH'
                      - $ref: '#/components/schemas/JHCoreDirectorAH'
                      - $ref: '#/components/schemas/JHSilverlakeAH'
                  creditDebitCode:
                    type: string
                    description: Indicates if the transaction is a debit or credit.
                  description:
                    type: string
                    description: Description of transaction.
                  eftDescriptionArray:
                    type: array
                    description: Array of remarks regarding the Electonic Funds Transfer.
                    items:
                      properties:
                        eftDescription:
                          type: string
                          description: Remark regarding the Electronic Funds Transfer.
                  status:
                    type: string
                    description: >-
                      Indicates the status of this transaction: 'A' Active, 'D'
                      Delete, 'L' Deposit List Post, 'X' Deposit Reversal, 'F'
                      Loan Fee, 'R' Loan Reversal.
                    enum:
                      - A
                      - D
                      - L
                      - X
                      - F
                      - R
                  transactionDate:
                    type: string
                    format: date
                    description: Date of transaction.
                  transactionID:
                    type: string
                    description: Unique identifier for the transaction.
                  transactionType:
                    type: string
                    description: Transaction category.
        statusCode:
          type: number
          description: Reference the `Codes` table.
        statusFlag:
          type: boolean
          description: >-
            Returns `true` if the post is successful. Returns `false` if any
            errors are encountered.
        statusMessage:
          type: string
          description: Details of the request `success` or `errors`.
        uuid:
          type: string
          description: Unique identifier for the request.
    AllNonStandardFields_AccountNumberGenerator:
      type: object
      description: All non-standard fields provided for Reserve Account Number request.
      properties:
        name:
          type: object
          description: Name of the account holder (JH SymXChange)
          properties:
            lastName:
              type: string
              description: Last name of the account holder. (JH SymXChange)
        openDate:
          type: string
          format: date
          description: Date account opened. (JH SymXChange)
        outputDepLoan:
          type: string
          description: Identifies output as a deposit or a loan. (Phoenix Finastra)
        preferenceType:
          type: string
          description: >-
            Credit union defined code to identify the preference record. (JH
            SymXChange)
    PhoenixAC:
      type: object
      description: Required fields for Phoenix cores.
      properties:
        outputDepLoan:
          type: string
          description: Identifies output as a deposit or a loan.
    SymXChangeAC:
      type: object
      description: Required fields for SymXChange cores.
      properties:
        name:
          type: object
          properties:
            lastName:
              type: string
              description: Last name of the account holder.
        openDate:
          type: string
          format: date
          description: Date account opened.
        preferenceType:
          type: string
          description: Credit union defined code to identify the preference record.
    AllNonStandardFields_AccountHistoryRq:
      type: object
      description: All non-standard fields provided for Account History Search request.
      properties:
        shareID:
          type: string
          description: Unique ID that identifies the share record. (JH SymXChange)
    SymXChangeAH:
      type: object
      description: Required fields for SymXChange cores.
      properties:
        shareID:
          type: string
          description: Unique ID that identifies the share record.
    AllNonStandardFields_AccountHistoryRs:
      type: object
      description: All non-standard fields provided for Account History Search response.
      properties:
        memoPost:
          type: object
          description: Memo post item. (JH 2020, JH CoreDirector, JH Silverlake)
          properties:
            memoDtEntry:
              type: string
              format: date
              description: >-
                The date the memo-posted item was created. (JH 2020, JH
                CoreDirector, JH Silverlake)
            memoPost:
              type: string
              description: >-
                Indicates if the transaction is a memo-posted item. (JH 2020, JH
                CoreDirector, JH Silverlake)
            memoTimeEntry:
              type: string
              description: >-
                The time of day that the memo-posted item was created. (JH 2020,
                JH CoreDirector, JH Silverlake)
            remarks:
              type: array
              description: >-
                An array of memo post remarks. (JH 2020, JH CoreDirector, JH
                Silverlake)
    JH2020AH:
      type: object
      description: Required fields for JXChange cores.
      properties:
        memoPost:
          type: object
          properties:
            memoDtEntry:
              type: string
              format: date
              description: The date the memo-posted item was created.
            memoPost:
              type: string
              description: Indicates if the transaction is a memo-posted item.
            memoTimeEntry:
              type: string
              description: The time of day that the memo-posted item was created.
            remarks:
              type: array
              description: An array of memo post remarks.
    JHCoreDirectorAH:
      type: object
      description: Required fields for JXChange cores.
      properties:
        memoPost:
          type: object
          properties:
            memoDtEntry:
              type: string
              format: date
              description: The date the memo-posted item was created.
            memoPost:
              type: string
              description: Indicates if the transaction is a memo-posted item.
            memoTimeEntry:
              type: string
              description: The time of day that the memo-posted item was created.
            remarks:
              type: array
              description: An array of memo post remarks.
    JHSilverlakeAH:
      type: object
      description: Required fields for JXChange cores.
      properties:
        memoPost:
          type: object
          properties:
            memoDtEntry:
              type: string
              format: date
              description: The date the memo-posted item was created.
            memoPost:
              type: string
              description: Indicates if the transaction is a memo-posted item.
            memoTimeEntry:
              type: string
              description: The time of day that the memo-posted item was created.
            remarks:
              type: array
              description: An array of memo post remarks.
security:
  - oAuth2: []
